### ISSUE TITLE
Fix up readme

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/HUCAgg#3]
The link to ftpext is wrong.

**Comment by ldecicco-USGS** [comment]
While you are at it.....
We just pushed this up to prod:
https://owi.usgs.gov/R/packages.html

I'd recommend this package as "Support" or "Research" (up to you). When you decide what you think this package could be, you could add a badge to your readme:

[![status](https://img.shields.io/badge/USGS-Support-yellow.svg)](https://owi.usgs.gov/R/packages.html#support)

If you wanted to include a link or note in your package startup message, we added that to some packages too.

**Comment by dblodgett-usgs** [comment]
Deff support.
